### DISCUSSION TITLE
Spark docker swarm 사용해서 구축해보기

### DISCUSSION THREAD

**Discussion by Kdreamtomaster** [WHATDO-TEAM/whatdo#33] [테스트 및 시연]
docker swarm 의 경우 기본 docker 환경과 같이 사용이 가능하고 
쿠버네티스에 비해 셋팅 및 운영이 상대적으로 간단하여 테스트 해보고 있습니다. 

1. Docker Swarm 클러스터 설정

1.1. Docker Swarm 초기화

> 	1.	마스터 노드 초기화
> server01에서 Swarm 클러스터를 초기화하여 마스터 노드로 설정합니다. Swarm 클러스터에 사용할 IP 주소를 지정합니다.

```
docker swarm init --advertise-addr <server01-IP>
```

> 
> 	•	--advertise-addr 옵션은 Swarm 클러스터의 메인 IP 주소로 지정할 서버의 IP를 입력합니다.
> 	•	이 명령어를 실행하면 나머지 노드(server02, server03)에서 Swarm에 참여하기 위한 join-token이 출력됩니다.
> 
> 	2.	워커 노드 추가
> 	        server02와 server03에서 Swarm 클러스터에 워커로 가입하기 위해 join-token 명령어를 실행합니다.

```
docker swarm join --token <TOKEN> <server01-IP>:2377
```

> 	•	<TOKEN> 부분은 docker swarm init 실행 시 출력된 join-token을 사용합니다.
> 	•	<server01-IP>는 server01의 IP 주소입니다.
> 
> 
> 	4.	Swarm 노드 확인
> server01에서 다음 명령어를 실행하여 Swarm에 제대로 노드들이 추가되었는지 확인합니다.

```
docker node ls
```

•	이 명령어는 현재 Swarm 클러스터의 모든 노드를 나열하며, server01은 리더(마스터)로, server02와 server03은 워커로 표시됩니다.

> 2. 네트워크 설정
> 
> Spark 클러스터가 통신할 수 있도록 Docker Swarm 오버레이 네트워크를 생성합니다. (server01 에서만 )

```
docker network create --driver overlay spark-net
```

	•	오버레이 네트워크는 여러 호스트에서 컨테이너 간 통신을 가능하게 합니다.
	•	이 네트워크는 Spark 클러스터 내의 모든 노드가 사용할 것입니다.

> 3. Docker Compose 파일 작성
> 
> Spark 마스터와 워커 노드를 특정 서버에 배포하기 위해 docker-compose-swarm.yml 파일을 작성합니다. 이 파일에서는 placement 옵션을 사용하여 노드 배치를 명시적으로 지정하고, 워커 노드의 포트를 설정하여 UI를 위한 접근성을 확보합니다.
> 
> docker-compose-swarm.yml 예시
> 

```

services:
  spark-master:
    image: bitnami/spark:latest
    hostname: spark-master
    networks:
      - spark-net
    ports:
      - "8080:8080"  # Spark Master UI 포트
      - "7077:7077"  # Spark Master 클러스터 포트
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no  # 보안 설정 (옵션)
      - SPARK_RPC_ENCRYPTION_ENABLED=no      # 보안 설정 (옵션)
    deploy:
      placement:
        constraints: [node.hostname == server01]  # Spark 마스터를 server01에 배포

  spark-worker-1:
    image: bitnami/spark:latest
    hostname: spark-worker-1
    networks:
      - spark-net
    ports:
      - "8081:8081"  # Worker 1 UI 포트
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_PORT=8081  # Worker UI 포트 설정
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    deploy:
      placement:
        constraints: [node.hostname == server02]  # Worker 1을 server02에 배포

  spark-worker-2:
    image: bitnami/spark:latest
    hostname: spark-worker-2
    networks:
      - spark-net
    ports:
      - "8082:8081"  # Worker 2 UI 포트를 8082로 매핑
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_PORT=8081  # Worker UI 포트 설정
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    deploy:
      placement:
        constraints: [node.hostname == server03]  # Worker 2를 server03에 배포

networks:
  spark-net:
    external: true

```

각 설정 항목 설명

	•	Spark Master 서비스
	•	SPARK_MODE=master: 마스터 노드로 설정합니다.
	•	SPARK_MASTER_URL: 각 워커는 이 주소로 마스터에 연결됩니다.
	•	포트 8080: Spark 마스터 UI 접근을 위한 포트.
	•	포트 7077: 클러스터 내의 노드들이 Spark 마스터와 통신하는 기본 포트입니다.
	•	Spark Worker 서비스
	•	SPARK_MODE=worker: 워커 노드로 설정합니다.
	•	SPARK_MASTER_URL: 마스터 노드의 URL을 지정하여 워커가 연결할 수 있도록 설정합니다.
	•	SPARK_WORKER_PORT: 워커 UI 포트를 지정하여 UI를 통해 각각의 워커 노드에 접근할 수 있습니다.
	•	각 워커는 placement 옵션을 통해 특정 서버에 배포되도록 설정했습니다.

5. Spark 클러스터 배포

서버1에서 docker stack deploy 명령어를 사용하여 Spark 클러스터를 Swarm에 배포합니다.

```
docker stack deploy -c docker-compose-swarm.yml spark-cluster
```

	•	이 명령어는 docker-compose-swarm.yml 파일에 정의된 설정을 기반으로 Swarm 클러스터에 Spark 클러스터를 배포합니다.

6. 클러스터 구성 및 모니터링

	1.	Spark 마스터 UI 접속
	•	Spark 마스터 UI는 http://<server01-IP>:8080에서 확인할 수 있습니다. 이 UI에서 클러스터 상태와 각 워커 노드의 연결 상태를 모니터링할 수 있습니다.
	2.	Spark 워커 UI 접속
	•	Spark 워커1 UI: http://<server02-IP>:8081
	•	Spark 워커2 UI: http://<server03-IP>:8082
각 워커 노드는 지정된 포트를 통해 개별적으로 UI에 접근할 수 있습니다.
	3.	Swarm 서비스 상태 확인
	•	Swarm 클러스터에서 실행 중인 서비스 상태는 다음 명령어로 확인할 수 있습니다.

```
docker service ls
```
