### DISCUSSION TITLE
에어플로우 가용성 - 스케쥴러 측면

### DISCUSSION THREAD

**Discussion by Kdreamtomaster** [WHATDO-TEAM/whatdo#9] [자료조사]
- 출처 : [에어플로우 가용성 - 스케쥴러 측면](https://kadensungbincho.tistory.com/9)
- 구조도 

<img width="691" alt="image" src="https://github.com/user-attachments/assets/313140ea-412d-4cad-a49e-78c90c9fb56f">

도커 컴포즈 메니페스토 파일

<details>

<summary>airflow </summary>

```
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=airflow
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=airflow
      - MYSQL_DATABASE=airflow
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3.8.0-management
    environment:
      - RABBITMQ_DEFAULT_USER=airflow
      - RABBITMQ_DEFAULT_PASS=airflow
      - RABBITMQ_DEFAULT_VHOST=airflow
    ports:
      - "15672:15672"

  master:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    image: puckel/docker-ha-airflow:1.10.9
    init: true
    hostname: master
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ${PWD}/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
      - ${PWD}/airflow/sshd_config:/etc/ssh/sshd_config
      - ${PWD}/airflow/.ssh:/usr/local/airflow/.ssh
    ports:
      - "8080:8080"
      - "2020:22"
    command: master

  worker:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    image: puckel/docker-ha-airflow:1.10.9
    init: true
    hostname: worker
    depends_on:
      - master
    ports:
      - "2021:22"
    volumes:
      - ${PWD}/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
      - ${PWD}/airflow/sshd_config:/etc/ssh/sshd_config
      - ${PWD}/airflow/.ssh:/usr/local/airflow/.ssh
    command: worker
```

</details>
