### ISSUE TITLE
MariaDB - MaxScale과 Galera Cluster 환경 설정

### ISSUE THREAD

**Issue by mfkim** [WHATDO-TEAM/whatdo#75]
- [x] Docker를 사용하여 MariaDB, MaxScale, Galera Cluster 환경 설정
- [x] Docker Compose 파일로 3개의 MariaDB 노드, MaxScale, 관리용 컨테이너 세팅
- [x] 네트워크 구성, 볼륨 마운트, 환경 변수 설정을 통한 클러스터 구성

**Comment by mfkim** [comment]
```shell
docker exec -it mariadb1 mysql -uroot -prootpassword

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 7
Server version: 10.5.26-MariaDB-ubu2004 mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> CREATE USER 'maxscale'@'%' IDENTIFIED BY 'maxscale_password';
Query OK, 0 rows affected (0.008 sec)

MariaDB [(none)]> GRANT ALL PRIVILEGES ON *.* TO 'maxscale'@'%' WITH GRANT OPTION;
Query OK, 0 rows affected (0.007 sec)

MariaDB [(none)]> FLUSH PRIVILEGES;
Query OK, 0 rows affected (0.010 sec)
```

**Comment by mfkim** [comment]
`docker-compose.yml`
```yml
version: '3'

services:
  mariadb1:
    image: mariadb:10.5
    container_name: mariadb1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - ./mariadb/galera.cnf:/etc/mysql/conf.d/galera.cnf
      - mariadb1_data:/var/lib/mysql
    command: --wsrep-new-cluster
    networks:
      - galera-network

  mariadb2:
    image: mariadb:10.5
    container_name: mariadb2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - ./mariadb/galera.cnf:/etc/mysql/conf.d/galera.cnf
      - mariadb2_data:/var/lib/mysql
    command: --wsrep-new-cluster
    networks:
      - galera-network
    depends_on:
      - mariadb1

  mariadb3:
    image: mariadb:10.5
    container_name: mariadb3
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - ./mariadb/galera.cnf:/etc/mysql/conf.d/galera.cnf
      - mariadb3_data:/var/lib/mysql 
    command: --wsrep-new-cluster
    networks:
      - galera-network
    depends_on:
      - mariadb1
      - mariadb2

  maxscale:
    image: mariadb/maxscale:latest
    container_name: maxscale
    volumes:
      - ./maxscale/maxscale.cnf:/etc/maxscale.cnf
    ports:
      - "4006:4006"  # MaxScale 서비스
      - "8989:8989"  # MaxScale 관리
    networks:
      - galera-network
    depends_on:
      - mariadb1
      - mariadb2
      - mariadb3

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - galera-network

networks:
  galera-network:
    driver: bridge

volumes:
  mariadb1_data:
  mariadb2_data:    
  mariadb3_data:    
```
